# Generated by Django 4.0.4 on 2022-05-20 18:30

from django.db import migrations, models
import hostel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=10)),
                ('hstl_name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('Bhubaneswar', 'Bhubaneswar'), ('Cuttack', 'Cuttack')], max_length=30)),
                ('type', models.CharField(choices=[('Boys Hostel', 'Boys Hostel'), ('Girls Hostel', 'Girls Hostel')], max_length=30)),
                ('zip', models.IntegerField(max_length=6)),
                ('rooms', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('ppw', models.IntegerField()),
                ('ppm', models.IntegerField()),
                ('rooms_avail', models.IntegerField()),
                ('aadhar', models.IntegerField()),
                ('id_proof', models.ImageField(blank=True, null=True, upload_to=hostel.models.get_filename)),
                ('images', models.ImageField(blank=True, null=True, upload_to=hostel.models.get_filename)),
            ],
        ),
    ]
