# Generated by Django 4.0.4 on 2022-05-21 03:10

from django.db import migrations, models
import hostel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_rename_type_hostel_detail_hstl_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel_detail',
            name='images',
        ),
        migrations.AddField(
            model_name='hostel_detail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=hostel.models.get_image),
        ),
        migrations.AlterField(
            model_name='hostel_detail',
            name='aadhar',
            field=models.CharField(max_length=12),
        ),
    ]
