# Generated by Django 4.0.4 on 2022-05-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_remove_hostel_detail_images_hostel_detail_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel_detail',
            old_name='hstl_name',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='hostel_detail',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
