# Generated by Django 4.0.4 on 2022-05-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_alter_hostel_detail_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel_detail',
            name='hstl_name',
            field=models.CharField(default='Hostel', max_length=100),
        ),
    ]
