# Generated by Django 4.0.4 on 2022-05-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_hostel_detail_hstl_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel_detail',
            name='locality',
        ),
        migrations.AddField(
            model_name='hostel_detail',
            name='latitude',
            field=models.CharField(default='0.0', max_length=50),
        ),
        migrations.AddField(
            model_name='hostel_detail',
            name='longitude',
            field=models.CharField(default='0.0', max_length=50),
        ),
    ]
