# Generated by Django 4.0.4 on 2022-05-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_hostel_detail_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_email', models.CharField(max_length=50)),
                ('cust_phone', models.CharField(max_length=50)),
                ('check_in', models.CharField(max_length=50)),
                ('pos', models.CharField(choices=[('1', '1 week'), ('2', '2 week'), ('3', '1 month'), ('4', '2 month'), ('5', '3 month'), ('6', '4 month'), ('7', '5 month'), ('8', '6 month')], max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('cust_id_proof', models.ImageField(upload_to='')),
                ('bed', models.CharField(max_length=50)),
                ('guest', models.CharField(max_length=50)),
                ('owner_uname', models.CharField(max_length=50)),
                ('hstl_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
