# Generated by Django 4.0.4 on 2022-05-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_activity_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_log',
            name='bed',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='guest',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='pos',
            field=models.CharField(max_length=30),
        ),
    ]
