# Generated by Django 4.0.4 on 2022-05-30 09:22

from django.db import migrations, models
import hostel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_alter_activity_log_bed_alter_activity_log_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_log',
            name='cust_id_proof',
            field=models.ImageField(blank=True, null=True, upload_to=hostel.models.get_idprof),
        ),
    ]
